/**
 * Legal Metrology Verification System - Constants & Statutory Enums
 * Department of Consumer Affairs (DoCA), Ministry of Consumer Affairs, Food & Public Distribution
 */

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  LEGAL_METROLOGY_OFFICER: 'LEGAL_METROLOGY_OFFICER',
  GATC_OFFICER: 'GATC_OFFICER',
  BUSINESS_USER: 'BUSINESS_USER',
  FIELD_VERIFICATION_OFFICER: 'FIELD_VERIFICATION_OFFICER',
};

export const USER_ROLE_LIST = Object.values(USER_ROLES);

export const APPLICATION_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SCHEDULED: 'SCHEDULED',
  INSPECTION: 'INSPECTION',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  CERTIFICATE_GENERATED: 'CERTIFICATE_GENERATED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const APPLICATION_STATUS_LIST = Object.values(APPLICATION_STATUSES);

/**
 * Statutory state transition machine rules.
 * Transitions outside this map are strictly forbidden and rejected with HTTP 400.
 */
export const ALLOWED_STATUS_TRANSITIONS = {
  [APPLICATION_STATUSES.DRAFT]: [
    APPLICATION_STATUSES.SUBMITTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.SUBMITTED]: [
    APPLICATION_STATUSES.UNDER_REVIEW,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.UNDER_REVIEW]: [
    APPLICATION_STATUSES.APPROVED,
    APPLICATION_STATUSES.SCHEDULED,
    APPLICATION_STATUSES.REJECTED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.APPROVED]: [
    APPLICATION_STATUSES.SCHEDULED,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.SCHEDULED]: [
    APPLICATION_STATUSES.INSPECTION,
    APPLICATION_STATUSES.CANCELLED,
  ],
  [APPLICATION_STATUSES.INSPECTION]: [
    APPLICATION_STATUSES.VERIFIED,
    APPLICATION_STATUSES.FAILED,
  ],
  [APPLICATION_STATUSES.VERIFIED]: [
    APPLICATION_STATUSES.CERTIFICATE_GENERATED,
  ],
  [APPLICATION_STATUSES.FAILED]: [
    APPLICATION_STATUSES.UNDER_REVIEW, // For re-inspection after rectification
  ],
  [APPLICATION_STATUSES.CERTIFICATE_GENERATED]: [
    APPLICATION_STATUSES.COMPLETED,
  ],
  [APPLICATION_STATUSES.REJECTED]: [],
  [APPLICATION_STATUSES.COMPLETED]: [],
  [APPLICATION_STATUSES.CANCELLED]: [],
};

export const APPLICATION_TYPES = {
  NEW_VERIFICATION: 'NEW_VERIFICATION',
  INITIAL_VERIFICATION: 'INITIAL_VERIFICATION',
  RE_VERIFICATION: 'RE_VERIFICATION',
  SUBSEQUENT_ANNUAL_VERIFICATION: 'SUBSEQUENT_ANNUAL_VERIFICATION',
  POST_REPAIR_VERIFICATION: 'POST_REPAIR_VERIFICATION',
};

export const APPLICATION_TYPE_LIST = Object.values(APPLICATION_TYPES);

export const SCHEDULE_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  SCHEDULED: 'SCHEDULED',
  RESCHEDULED: 'RESCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const SCHEDULE_STATUS_LIST = Object.values(SCHEDULE_STATUSES);

export const ALLOWED_SCHEDULE_STATUS_TRANSITIONS = {
  [SCHEDULE_STATUSES.PENDING]: [
    SCHEDULE_STATUSES.CONFIRMED,
    SCHEDULE_STATUSES.SCHEDULED,
    SCHEDULE_STATUSES.CANCELLED,
  ],
  [SCHEDULE_STATUSES.CONFIRMED]: [
    SCHEDULE_STATUSES.IN_PROGRESS,
    SCHEDULE_STATUSES.RESCHEDULED,
    SCHEDULE_STATUSES.CANCELLED,
  ],
  [SCHEDULE_STATUSES.SCHEDULED]: [
    SCHEDULE_STATUSES.CONFIRMED,
    SCHEDULE_STATUSES.IN_PROGRESS,
    SCHEDULE_STATUSES.RESCHEDULED,
    SCHEDULE_STATUSES.CANCELLED,
  ],
  [SCHEDULE_STATUSES.RESCHEDULED]: [
    SCHEDULE_STATUSES.CONFIRMED,
    SCHEDULE_STATUSES.SCHEDULED,
    SCHEDULE_STATUSES.IN_PROGRESS,
    SCHEDULE_STATUSES.CANCELLED,
  ],
  [SCHEDULE_STATUSES.IN_PROGRESS]: [
    SCHEDULE_STATUSES.COMPLETED,
    SCHEDULE_STATUSES.CANCELLED,
  ],
  [SCHEDULE_STATUSES.COMPLETED]: [],
  [SCHEDULE_STATUSES.CANCELLED]: [],
};

export const INSTRUMENT_STATUSES = {
  ACTIVE_VERIFIED: 'ACTIVE_VERIFIED',
  EXPIRED: 'EXPIRED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  REJECTED: 'REJECTED',
  OUT_OF_SERVICE: 'OUT_OF_SERVICE',
};

export const INSTRUMENT_STATUS_LIST = Object.values(INSTRUMENT_STATUSES);

export const INSTRUMENT_CATEGORIES = {
  NON_AUTOMATIC_WEIGHING_INSTRUMENT: 'NON_AUTOMATIC_WEIGHING_INSTRUMENT',
  NON_AUTOMATIC_WEIGHING_INSTRUMENTS: 'NON_AUTOMATIC_WEIGHING_INSTRUMENT',
  AUTOMATIC_WEIGHING_INSTRUMENT: 'AUTOMATIC_WEIGHING_INSTRUMENT',
  FUEL_DISPENSER: 'FUEL_DISPENSER',
  FLOW_METER: 'FLOW_METER',
  WEIGHBRIDGE: 'WEIGHBRIDGE',
  COUNTER_SCALE: 'COUNTER_SCALE',
  PRECISION_BALANCE: 'PRECISION_BALANCE',
  MEASURING_TAPE: 'MEASURING_TAPE',
  STORAGE_TANK_CALIBRATION: 'STORAGE_TANK_CALIBRATION',
};

export const INSTRUMENT_CATEGORY_LIST = Object.values(INSTRUMENT_CATEGORIES);

export const ACCURACY_CLASSES = {
  CLASS_I_SPECIAL: 'CLASS_I_SPECIAL',
  CLASS_II_HIGH: 'CLASS_II_HIGH',
  CLASS_III_MEDIUM: 'CLASS_III_MEDIUM',
  CLASS_IIII_ORDINARY: 'CLASS_IIII_ORDINARY',
};

export const ACCURACY_CLASS_LIST = Object.values(ACCURACY_CLASSES);

export const CERTIFICATE_STATUSES = {
  ACTIVE: 'ACTIVE',
  VALID: 'VALID',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
  CANCELLED: 'CANCELLED',
};

export const CERTIFICATE_STATUS_LIST = Object.values(CERTIFICATE_STATUSES);

export const ALLOWED_CERTIFICATE_STATUS_TRANSITIONS = {
  [CERTIFICATE_STATUSES.ACTIVE]: [
    CERTIFICATE_STATUSES.EXPIRED,
    CERTIFICATE_STATUSES.REVOKED,
    CERTIFICATE_STATUSES.CANCELLED,
  ],
  [CERTIFICATE_STATUSES.VALID]: [
    CERTIFICATE_STATUSES.EXPIRED,
    CERTIFICATE_STATUSES.REVOKED,
    CERTIFICATE_STATUSES.CANCELLED,
  ],
  [CERTIFICATE_STATUSES.EXPIRED]: [
    CERTIFICATE_STATUSES.REVOKED,
  ],
  [CERTIFICATE_STATUSES.REVOKED]: [],
  [CERTIFICATE_STATUSES.CANCELLED]: [],
};

export const VERIFICATION_VERDICTS = {
  PASS: 'PASS',
  FAIL: 'FAIL',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const VERIFICATION_VERDICT_LIST = Object.values(VERIFICATION_VERDICTS);

export const NOTIFICATION_TYPES = {
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REVIEWED: 'APPLICATION_REVIEWED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  SCHEDULE_CREATED: 'SCHEDULE_CREATED',
  SCHEDULE_CHANGED: 'SCHEDULE_CHANGED',
  SCHEDULE_CANCELLED: 'SCHEDULE_CANCELLED',
  VERIFICATION_SCHEDULED: 'VERIFICATION_SCHEDULED',
  INSPECTION_ASSIGNED: 'INSPECTION_ASSIGNED',
  INSPECTION_COMPLETED: 'INSPECTION_COMPLETED',
  VERIFICATION_PASSED: 'VERIFICATION_PASSED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  CERTIFICATE_ISSUED: 'CERTIFICATE_ISSUED',
  CERTIFICATE_GENERATED: 'CERTIFICATE_GENERATED',
  CERTIFICATE_EXPIRING_60: 'CERTIFICATE_EXPIRING_60',
  CERTIFICATE_EXPIRING_30: 'CERTIFICATE_EXPIRING_30',
  CERTIFICATE_EXPIRING_15: 'CERTIFICATE_EXPIRING_15',
  CERTIFICATE_EXPIRING_7: 'CERTIFICATE_EXPIRING_7',
  CERTIFICATE_EXPIRED: 'CERTIFICATE_EXPIRED',
  VERIFICATION_DUE: 'VERIFICATION_DUE',
  VERIFICATION_OVERDUE: 'VERIFICATION_OVERDUE',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
};

export const NOTIFICATION_TYPE_LIST = Object.values(NOTIFICATION_TYPES);

export const NOTIFICATION_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const NOTIFICATION_PRIORITY_LIST = Object.values(NOTIFICATION_PRIORITIES);

export const DYNAMIC_CERTIFICATE_STATUSES = {
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
  CANCELLED: 'CANCELLED',
};

export const DYNAMIC_CERTIFICATE_STATUS_LIST = Object.values(DYNAMIC_CERTIFICATE_STATUSES);

export const INSTRUMENT_DUE_STATUSES = {
  UP_TO_DATE: 'UP_TO_DATE',
  DUE_SOON: 'DUE_SOON',
  OVERDUE: 'OVERDUE',
};

export const INSTRUMENT_DUE_STATUS_LIST = Object.values(INSTRUMENT_DUE_STATUSES);

export const INSPECTION_STATUSES = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  REQUIRES_CORRECTION: 'REQUIRES_CORRECTION',
  CANCELLED: 'CANCELLED',
};

export const INSPECTION_STATUS_LIST = Object.values(INSPECTION_STATUSES);

export const ALLOWED_INSPECTION_STATUS_TRANSITIONS = {
  [INSPECTION_STATUSES.DRAFT]: [
    INSPECTION_STATUSES.IN_PROGRESS,
    INSPECTION_STATUSES.CANCELLED,
  ],
  [INSPECTION_STATUSES.IN_PROGRESS]: [
    INSPECTION_STATUSES.SUBMITTED,
    INSPECTION_STATUSES.DRAFT,
    INSPECTION_STATUSES.CANCELLED,
  ],
  [INSPECTION_STATUSES.SUBMITTED]: [
    INSPECTION_STATUSES.UNDER_REVIEW,
    INSPECTION_STATUSES.PASSED,
    INSPECTION_STATUSES.FAILED,
    INSPECTION_STATUSES.REQUIRES_CORRECTION,
  ],
  [INSPECTION_STATUSES.UNDER_REVIEW]: [
    INSPECTION_STATUSES.PASSED,
    INSPECTION_STATUSES.FAILED,
    INSPECTION_STATUSES.REQUIRES_CORRECTION,
  ],
  [INSPECTION_STATUSES.REQUIRES_CORRECTION]: [
    INSPECTION_STATUSES.IN_PROGRESS,
    INSPECTION_STATUSES.SUBMITTED,
    INSPECTION_STATUSES.CANCELLED,
  ],
  [INSPECTION_STATUSES.PASSED]: [
    INSPECTION_STATUSES.UNDER_REVIEW, // Controlled reopen by authorized admin
  ],
  [INSPECTION_STATUSES.FAILED]: [
    INSPECTION_STATUSES.UNDER_REVIEW, // Controlled reopen by authorized admin
  ],
  [INSPECTION_STATUSES.CANCELLED]: [],
};

export const INSPECTION_RESULTS = {
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  CONDITIONAL: 'CONDITIONAL',
  PENDING: 'PENDING',
};

export const INSPECTION_RESULT_LIST = Object.values(INSPECTION_RESULTS);

export const DEFECT_SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const DEFECT_SEVERITY_LIST = Object.values(DEFECT_SEVERITIES);

export const AUDIT_ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  STAKEHOLDER_CREATED: 'STAKEHOLDER_CREATED',
  STAKEHOLDER_UPDATED: 'STAKEHOLDER_UPDATED',
  INSTRUMENT_REGISTERED: 'INSTRUMENT_REGISTERED',
  INSTRUMENT_UPDATED: 'INSTRUMENT_UPDATED',
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_UPDATED: 'APPLICATION_UPDATED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_STATUS_UPDATED: 'APPLICATION_STATUS_UPDATED',
  APPLICATION_REVIEWED: 'APPLICATION_REVIEWED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  SCHEDULE_ASSIGNED: 'SCHEDULE_ASSIGNED',
  SCHEDULE_CREATED: 'SCHEDULE_CREATED',
  SCHEDULE_CONFIRMED: 'SCHEDULE_CONFIRMED',
  SCHEDULE_RESCHEDULED: 'SCHEDULE_RESCHEDULED',
  SCHEDULE_CANCELLED: 'SCHEDULE_CANCELLED',
  SCHEDULE_STARTED: 'SCHEDULE_STARTED',
  SCHEDULE_COMPLETED: 'SCHEDULE_COMPLETED',
  OFFICER_ASSIGNED: 'OFFICER_ASSIGNED',
  FIELD_OFFICER_ASSIGNED: 'FIELD_OFFICER_ASSIGNED',
  CENTER_ASSIGNED: 'CENTER_ASSIGNED',
  GATC_ASSIGNED: 'GATC_ASSIGNED',
  INSPECTION_RECORDED: 'INSPECTION_RECORDED',
  INSPECTION_STARTED: 'INSPECTION_STARTED',
  INSPECTION_DRAFT_SAVED: 'INSPECTION_DRAFT_SAVED',
  INSPECTION_SUBMITTED: 'INSPECTION_SUBMITTED',
  INSPECTION_FINALIZED: 'INSPECTION_FINALIZED',
  INSPECTION_REOPENED: 'INSPECTION_REOPENED',
  INSPECTION_EVIDENCE_UPLOADED: 'INSPECTION_EVIDENCE_UPLOADED',
  VERIFICATION_RESULT_CREATED: 'VERIFICATION_RESULT_CREATED',
  CERTIFICATE_GENERATED: 'CERTIFICATE_GENERATED',
  CERTIFICATE_REVOKED: 'CERTIFICATE_REVOKED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_PREFERENCE_UPDATED: 'NOTIFICATION_PREFERENCE_UPDATED',
  EXPIRY_CHECK_EXECUTED: 'EXPIRY_CHECK_EXECUTED',
  DUE_DATE_ALERT_DISPATCHED: 'DUE_DATE_ALERT_DISPATCHED',
};
